mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    #url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^stock/', include('stock.urls', namespace='stock', app_name='stock')),
]

stock/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from .apps import StockConfig
#import xlrd, xlwt, sys, os, datetime
#sys.path.insert(0, StockConfig.TSL_PATH)
#import TSLPy3
#if TSLPy3.Logined():
#    pass
#else:
#    result = TSLPy3.DefaultConnectAndLogin(StockConfig.TSL_LOGIN_NAME)
#    print(result[0])

urlpatterns = [
    
]

stock/models.py
from django.db import models


class StockSection(models.Model):
    sectionName = models.CharField(max_length=300)
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    stockId2 = models.CharField(max_length=300, null=True) #华尔街见闻用
    sectionId = models.CharField(max_length=300, null=True)

    class Meta:
        ordering = ("-sectionName",)

    def __str__(self):
        return self.sectionName, ':', self.stockName

class SectionInfo(models.Model):
    sectionId = models.CharField(max_length=300, null=True)
    sectionName = models.CharField(max_length=300)
    desc = models.TextField(null=True)

    class Meta:
        ordering = ("-sectionName",)

class StockSectionTemp(models.Model):
    sectionName = models.CharField(max_length=300)
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    stockId2 = models.CharField(max_length=300, null=True) #华尔街见闻用
    sectionId = models.CharField(max_length=300, null=True)

    class Meta:
        ordering = ("-sectionName",)

    def __str__(self):
        return self.sectionName, ':', self.stockName

class SectionInfoTemp(models.Model):
    sectionId = models.CharField(max_length=300, null=True)
    sectionName = models.CharField(max_length=300)
    desc = models.TextField(null=True)

    class Meta:
        ordering = ("-sectionName",)

class News(models.Model):
    datetime = models.CharField(max_length=32)
    title = models.CharField(max_length=512)
    isbull = models.CharField(max_length=32)
    content = models.TextField(null=True)
    stocks = models.CharField(max_length=512, null=True)
    sections = models.CharField(max_length=512, null=True)

    class Meta:
        ordering = ("-datetime",)

    def __str__(self):
        return self.datetime, ':', self.title

class StockComment(models.Model):
    stockId = models.CharField(max_length=32)
    comment = models.TextField()
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    created = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ("-like",)

    def __str__(self):
        return self.stockId, ':', self.comment

class StockWatchList(models.Model):
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    priority = models.IntegerField(default=0)

    class Meta:
        ordering = ("priority",)

    def __str__(self):
        return self.stockId, ':', self.stockName

class ImportantStock(models.Model):
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300, blank=True)
    position = models.IntegerField(default=0)

    class Meta:
        ordering = ("position",)

    def __str__(self):
        return self.stockId, ':', self.position

class ImportantStockMarket(models.Model):
    stockId = models.CharField(max_length=30)
    stockName = models.CharField(max_length=100, blank=True)
    position = models.IntegerField(default=0)
    increaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    increaseRateStr = models.CharField(max_length=100, blank=True)
    limitUpTime = models.CharField(max_length=30)
    sections = models.CharField(max_length=300)
    klineType = models.CharField(max_length=300)

    class Meta:
        ordering = ("position",)

    def __str__(self):
        return self.stockId, ':', self.position

class StockMarketIndex(models.Model):
    date = models.CharField(max_length=10)
    #sh
    indexSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrSH = models.CharField(max_length=100, blank=True)
    increaseStockSH = models.IntegerField(default=0)
    decreaseStockSH = models.IntegerField(default=0)
    flatStockSH = models.IntegerField(default=0)
    limitupStcokSH = models.IntegerField(default=0)
    limitdownStcokSH = models.IntegerField(default=0)
    longRedStcokSH = models.IntegerField(default=0)
    longGreenStcokSH = models.IntegerField(default=0)
    #sz
    indexSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrSZ = models.CharField(max_length=100, blank=True)
    increaseStockSZ = models.IntegerField(default=0)
    decreaseStockSZ = models.IntegerField(default=0)
    flatStockSZ = models.IntegerField(default=0)
    limitupStcokSZ = models.IntegerField(default=0)
    limitdownStcokSZ = models.IntegerField(default=0)
    longRedStcokSZ = models.IntegerField(default=0)
    longGreenStcokSZ = models.IntegerField(default=0)
    #zxb
    indexZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrZXB = models.CharField(max_length=100, blank=True)
    increaseStockZXB = models.IntegerField(default=0)
    decreaseStockZXB = models.IntegerField(default=0)
    flatStockZXB = models.IntegerField(default=0)
    limitupStcokZXB = models.IntegerField(default=0)
    limitdownStcokZXB = models.IntegerField(default=0)
    longRedStcokZXB = models.IntegerField(default=0)
    longGreenStcokZXB = models.IntegerField(default=0)
    #cyb
    indexCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrCYB = models.CharField(max_length=100, blank=True)
    increaseStockCYB = models.IntegerField(default=0)
    decreaseStockCYB = models.IntegerField(default=0)
    flatStockCYB = models.IntegerField(default=0)
    limitupStcokCYB = models.IntegerField(default=0)
    limitdownStcokCYB = models.IntegerField(default=0)
    longRedStcokCYB = models.IntegerField(default=0)
    longGreenStcokCYB = models.IntegerField(default=0)
    #total
    limitupStcokTotal = models.IntegerField(default=0)
    limitupNormalStcokTotal = models.IntegerField(default=0)
    limitupOneTypeStcokTotal = models.IntegerField(default=0)
    limitupTTypeStcokTotal = models.IntegerField(default=0)
    limitupFirstStcokTotal = models.IntegerField(default=0)
    limitupSencondStcokTotal = models.IntegerField(default=0)
    limitupThirdStcokTotal = models.IntegerField(default=0)
    badLimitupStcokTotal = models.IntegerField(default=0)
    badLimitupFirstStcokTotal = models.IntegerField(default=0)
    badLimitupSencondStcokTotal = models.IntegerField(default=0)
    badLimitupThirdStcokTotal = models.IntegerField(default=0)
    limitdownStcokTotal = models.IntegerField(default=0)
    limitdownFirstStcokTotal = models.IntegerField(default=0)
    limitdownSencondStcokTotal = models.IntegerField(default=0)
    limitdownThirdStcokTotal = models.IntegerField(default=0)

    class Meta:
        ordering = ("-date",)

    def __str__(self):
        return self.date

class SectionIncreaseInfo(models.Model):
    date = models.CharField(max_length=10)
    sectionName = models.CharField(max_length=300)
    sectionIncreaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed2minRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed2minRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed5MinRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed5MinRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed30MinRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed30MinRateStr = models.CharField(max_length=300)

    class Meta:
        ordering = ("-date",)

    def __str__(self):
        return self.sectionName

class SectionMarketInfo(models.Model):
    date = models.CharField(max_length=10, blank=True)
    sectionName = models.CharField(max_length=300)
    sectionIncreaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseRateStr = models.CharField(max_length=300)
    increaseCount = models.IntegerField(default=0)
    decreaseCount = models.IntegerField(default=0)
    totalCount = models.IntegerField(default=0)
    limitUpCount = models.IntegerField(default=0)
    limitUpStocksShow = models.CharField(max_length=300, blank=True)
    limitUpStocksHidden = models.CharField(max_length=300, blank=True)
    badLimitUpCount = models.IntegerField(default=0)
    badLimitUpStocksShow = models.CharField(max_length=300, blank=True)
    badLimitUpStocksHidden = models.CharField(max_length=300, blank=True)
    threeStraightLimitUp = models.IntegerField(default=0)
    specialStockShow = models.CharField(max_length=300, blank=True)
    specialStockHidden = models.CharField(max_length=300, blank=True)
    newsList = []

    class Meta:
        ordering = ("-sectionIncreaseRate",)

    def __str__(self):
        return self.sectionName, ':', self.sectionIncreaseRateStr

class StockLimitUp(models.Model):
    date = models.CharField(max_length=10)
    stockId = models.CharField(max_length=32)
    stockName = models.CharField(max_length=100)
    limitUpInfo = models.CharField(max_length=100)
    limitUpTime = models.CharField(max_length=32)
    rank = models.IntegerField(default=0)

    class Meta:
        ordering = ("rank",)

    def __str__(self):
        return self.stockId, ':', self.limitUpInfo

class StockIncreaseFastWithAmount(models.Model):
    date = models.CharField(max_length=10)
    stockId = models.CharField(max_length=32)
    stockName = models.CharField(max_length=100)
    time = models.CharField(max_length=30, blank=True)

    class Meta:

stock/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import StockSection, SectionInfo, StockWatchList


class StockSectionForm(forms.ModelForm):
    class Meta:
        model = StockSection
        fields = ("sectionName", "stockId", "stockName")


class SectionInfoForm(forms.ModelForm):
    class Meta:
        model = SectionInfo
        fields = ("sectionName", "sectionId")

class StockWatchListForm(forms.ModelForm):
    class Meta:
        model = StockWatchList
        fields = ("stockId", "stockName", "priority")    

stock/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse, FileResponse
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.core import serializers

templates/stock/section/section.html
{% extends "stock/base.html "%}

{% load staticfiles %}

{% block title %}JYU{% endblock%}

{% block content%}

<div>
    <table class="table table-hover" id="table">
        <thead>
            <td>板块名称</td>
            <td>板块涨幅</td>
            <td>板块涨速</td>
            <td>领涨股</td>
            <td>涨家数</td>
            <td>跌家数</td>
            <td>换手</td>
            <td>金额</td>
            <td>总手</td>
            <td>资讯</td>
        </thead>
        {% for section in sectionList %}
            <tr>
                <td><a href="/stock/section_market_info?sectionid={{ section.sectionId }}" target="_Blank">{{ section.sectionName }}</a></td>
                <td style="color:{%if section.sectionIncreaseRate > 0%}#e52222{%endif%}{%if section.sectionIncreaseRate < 0%}#18a66b{%endif%}">{{ section.sectionIncreaseRateStr }}</td>
                <td></td>
                <td>{{ section.mostIncreaseStockName }}{{ section.mostIncreaseIncreateRateStr }}</td>
                <td>{{ section.increaseCount }}</td>
                <td>{{ section.decreaseCount }}</td>
                <td>{{ section.change }}</td>
                <td>{{ section.amount }}</td>
                <td>{{ section.num }}</td>
                <td>
                    <p sytle="color:red" title="{% for news in section.newsList %}
                    {{news.datetime}} : {{news.title}}.
                    {% endfor %}">{{section.newsCount}}</p>
                </td>
            </tr>
        {% endfor%}
    </table>
    {% if errorMsg != '' %}
    <div class="alert alert-danger">{{ errorMsg }}</div>
    {% endif %}
    <!--
    {% include "paginator.html "%} -->
</div>
<script type="text/javascript">
$(document).ready(function(){
        $("#table").DataTable({
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "order": [[ 1, "desc" ]]
        });
    });
$.extend( $.fn.dataTableExt.oStdClasses, {
    "sWrapper": "dataTables_wrapper form-inline"
} );
</script>
{% endblock %}

templates/stock/section/section_list.html
{% extends "stock/base_single.html "%}

{% load staticfiles %}

{% block title %}JYU{% endblock%}

{% block content%}
<div>
     <p class="text-left">板块名称：{{sectionInfoForm.sectionName}}
    </p>
    <p class="text-right">
    <button class="btn btn-primary" id="query" onclick="query()">查询</button>
    <button class="btn btn-primary" id="add_section" onclick="add_section()">新增板块</button>
    <button class="btn btn-primary" id="merge_section" onclick="merge_section()">合并板块</button>
    </p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>板块名称</td>
            <td>板块简介</td>
            <td>操作</td>
        </tr>
        {% for row in list %}
        <tr id="{{row.id}}">
            <td>{{ forloop.counter }}</td>
            <td><a href="/stock/section_market_info?sectionid={{row.id}}">{{ row.sectionName }}</a></td>
            <td>{{ row.desc }}</td>
            <td>
            <a name="edit" href="javascript:" onclick="edit_section(this,{{row.id}},'{{row.sectionName}}')" title="修改板块"> <span class="glyphicon glyphicon-pencil"></span>
                </a>
            <a name="add_stock" href="javascript:" onclick="add_stock(this,'{{row.sectionName}}')" title="添加股票"><span class="glyphicon glyphicon-plus-sign" style="margin-left:20px"></span></a>
            <a name="delete" href="javascript:" onclick="del_section(this,{{row.id}},'{{row.sectionName}}')" title="删除板块"><span class="glyphicon glyphicon-trash" style="margin-left:20px"></span></a>
                </td>
        </tr>
        {% endfor %}
    </table>

    {% include "paginator.html "%}
</div>
<script type="text/javascript" src="{% static "js/jquery.js"%}"></script>
<script type="text/javascript" src="{% static "js/layer.js"%}"></script>
<script type="text/javascript">
function query(){
url = "?page=1&sectionName=" + $("#id_sectionName").val();
location.replace(url) ;

}

    function add_section(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"新增板块",
            content:'<div class="text-center" style="margin-top:20px"><p>请输入板块名称</p><p>{{sectionInfoForm.sectionName}}</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                section_name = $('#id_sectionName').val();
                $.ajax({
                    url:'{% url "stock:addSection"%}',
                    type:'POST',
                    data:{"section_name":section_name},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("创建成功");
                        }else{
                            layer.msg("板块名称重复，请重新输入");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function edit_section(the,id,name){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"编辑板块名称",
            content:'<div class="text-center" style="margin-top:20px"><p>请编辑板块名称</p><p><input type="text" id="new_name" value="' + name +'"></p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                new_name = $('#new_name').val();
                $.ajax({
                    url:'{% url "stock:editSection"%}',
                    type:'POST',
                    data:{"id":id,"section_name":new_name},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("编辑成功");
                        }else{
                            layer.msg("编辑失败");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function del_section(the,id,name){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"删除板块",
            content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除' + name +'栏目</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                $.ajax({
                    url:'{% url "stock:deleteSection"%}',
                    type:'POST',
                    data:{"id":id},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("删除成功");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function add_stock(the,sectionName){
        var name = $(the).parents("tr").children("td").eq(1).text()
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["500px","400px"],
            title:"add stock",
            content:'<div class="text-center" style="margin-top:20px"><p>请输入股票代码</p><p>{{stockSectionForm.stockId}}</p></div><div class="text-center" style="margin-top:20px"><p>请输入股票名称</p><p>{{stockSectionForm.stockName}}</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                stockId = $('#id_stockId').val();
                stockName = $('#id_stockName').val();
                $.ajax({
                    url:'{% url "stock:addStock"%}',
                    type:'POST',
                    data:{"sectionName":sectionName,"stockId":stockId,"stockName":stockName},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("添加成功");
                        }else{
                            layer.msg("添加失败");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function merge_section(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["500px","400px"],
            title:"merge section",
            content:'<div class="text-center" style="margin-top:20px"><p>请选择板块</p><p><select id="section1">{{sectionListHtml|safe}}</select></p></div>' + 
            '<div class="text-center" style="margin-top:20px"><p>请选择板块</p><p><select id="section2">{{sectionListHtml|safe}}</select></p></div>' + 
            '<div class="text-center" style="margin-top:20px"><p>请输入板块名称</p><p>{{sectionInfoForm.sectionName}}</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                id1 = $('#section1').val();
                id2 = $('#section2').val();
                sectionName = $('#id_sectionName').val();
                if(id1 != id2){
                    $.ajax({
                        url:'{% url "stock:mergeSection"%}',
                        type:'POST',
                        data:{"id1":id1,"id2":id2,"sectionName":sectionName},
                        success:function(e){
                            if(e=='1'){
                                parent.location.reload();
                                layer.msg("添加成功");
                            }else if(e=='2'){
                                layer.msg("板块名称重复，添加失败");
                            }else if(e=='3'){
                                layer.msg("不能选择两个相同的板块");
                            }else{
                                layer.msg("添加失败");
                            }
                        },
                    });
                }else{
                    layer.msg("不能选择两个相同的板块");
                }

            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

</script>
{% endblock %}

templates/stock/section/stock_section_list.html
{% extends "stock/base_single.html"%}

{% load staticfiles %}

{% block title %}JYU{% endblock%}

{% block content%}
<div>
    <p class="text-left">板块名称：{{stockSectionForm.sectionName}}
    股票代码：{{stockSectionForm.stockId}}
    股票名称：{{stockSectionForm.stockName}}
    </p>
    <p class="text-right"><button class="btn btn-primary" id="query" onclick="query()">查询</button>
    <button class="btn btn-primary" id="add_stock" onclick="add_stock()">添加信息</button>
    <button class="btn btn-primary" id="synToTysoft" onclick="synToTysoft()">同步至天软</button>
    <button class="btn btn-primary" id="batch_import" onclick="batch_import()">批量导入</button></p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>板块名称</td>
            <td>股票代码</td>
            <td>股票名称</td>
            <td>操作</td>
        </tr>
        {% for row in list %}
        <tr id="{{row.stockId}}">
            <td>{{ forloop.counter }}</td>
            <td><a href="/stock/section_market_info?sectionname={{row.sectionName}}">{{ row.sectionName }}</a></td>
            <td><a href="/stock/stock_info?stockid={{ row.stockId }}" target="_Blank">{{ row.stockId }}</a></td>
            <td>{{ row.stockName }}</td>
            <td>
            <a name="delete" href="javascript:" onclick="del_stock(this,'{{row.id}}','{{row.stockName}}')"><span class="glyphicon glyphicon-trash" style="margin-left:20px"></span></a>
            </td>
        </tr>
        {% endfor%}
    </table>

    {% include "paginator.html "%}
    
    {% if errorMsg != '' %}
    <div class="alert alert-danger">{{ errorMsg }}</div>
    {% endif %}
</div>
<form type="submit" action="{% url 'stock:stockSectionList'%}" id="submitForm">
<input type="hidden" name="sectionName" id="submitSectionName">
<input type="hidden" name="stockId"  id="submitStockId">
<input type="hidden" name="stockName"  id="submitStockName">
</form>
<script type="text/javascript" src="{% static "js/jquery.js"%}"></script>
<script type="text/javascript" src="{% static "js/layer.js"%}"></script>
<script type="text/javascript">

    function query(){
//url = "?page=1&sectionName=" + $("#id_sectionName").val() + "&stockId=" +  $("#id_stockId").val() + "&stockName=" +  $("#id_stockName").val()
//location.replace(url)

var form = $("#submitForm");
$("#submitSectionName").val($("#id_sectionName").val());
$("#submitStockId").val($("#id_stockId").val());
$("#submitStockName").val($("#id_stockName").val());
form.submit();
}


    function del_stock(the,id,name){
        var name = $(the).parents("tr").children("td").eq(1).text()
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"删除股票",
            content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除{' + name +'}</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                $.ajax({
                    url:'{% url "stock:deleteStock"%}',
                    type:'POST',
                    data:{"id":id},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("删除成功");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function add_stock(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["500px","400px"],
            title:"add stock",
            content:'<div class="text-center" style="margin-top:20px"><p>请选择板块</p><p><select id="sectionName">{{sectionListHtml|safe}}</select></p></div>' +
            '<div class="text-center" style="margin-top:20px"><p>请输入股票代码</p><p>{{stockSectionForm.stockId}}</p></div>' +
            '<div class="text-center" style="margin-top:20px"><p>请输入股票名称</p><p>{{stockSectionForm.stockName}}</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                stockId = $('#sectionName').val();
                stockId = $('#id_stockId').val();
                stockName = $('#id_stockName').val();
                $.ajax({
                    url:'{% url "stock:addStock"%}',
                    type:'POST',
                    data:{"sectionName":sectionName,"stockId":stockId,"stockName":stockName},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("添加成功");
                        }else{
                            layer.msg("添加失败");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }
    
    function batch_import(){
        layer.open({
          type: 2,
          title: '批量导入',
          shadeClose: true,
          shade: 0.8,
          area:["500px","400px"],
          content: '{% url "stock:batchImport"%}'
        }); 
    }


    function synToTysoft(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"同步至天软",
            content:'<div class="text-center" style="margin-top:20px"><p>是否要将信息同步至天软？</p><p>温馨提示：尽量不要在交易时间进行本操作。</p></div>',
            btn:['确认','取消'],
            yes:function(index,layero){
                $.ajax({
                    url:'{% url "stock:synToTysoft"%}',
                    type:'POST',
                    data:{},
                    layerIndex:-1,
                    beforeSend: function () { //插件加载前
                        this.layerIndex = layer.load(0, { shade: [0.01, '#fff'] });
                    },
                    success:function(result){
                        layer.close(this.layerIndex);
                        layer.close(index)
                        layer.msg(result);
                    }
            })},
            btn2:function(index,layero){
                layer.close(this.layerIndex);
                layer.close(index)
            }
        });
    }
    

</script>
{% endblock %}

templates/stock/section/upload.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
   <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<form enctype="multipart/form-data" method="post" action="{% url 'stock:batchImport'%}">
    {% csrf_token %}
    <div class="form-group  text-center">
        <label for="exampleInputFile">板块名称</label>
        <select name="sectionName">
        {{sectionListHtml|safe}}
        </select>
        <label for="exampleInputFile">选择文件</label>
        <input type="file"  name="uploadFile">
    </div>
  
    <div class="col-lg-offset-3 text-center">
     <button class="btn btn-primary" type="submit">批量导入</button>
    </div>
 
</form>
{{ result }}
</body>
<script type="text/javascript" src="{% static "js/jquery.js"%}"></script>
<script type="text/javascript" src="{% static "js/layer.js"%}"></script>