mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    #url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^stock/', include('stock.urls', namespace='stock', app_name='stock')),
]

stock/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from .apps import StockConfig
#import xlrd, xlwt, sys, os, datetime
#sys.path.insert(0, StockConfig.TSL_PATH)
#import TSLPy3
#if TSLPy3.Logined():
#    pass
#else:
#    result = TSLPy3.DefaultConnectAndLogin(StockConfig.TSL_LOGIN_NAME)
#    print(result[0])

urlpatterns = [
    
]

stock/models.py
from django.db import models


class StockSection(models.Model):
    sectionName = models.CharField(max_length=300)
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    stockId2 = models.CharField(max_length=300, null=True) #华尔街见闻用
    sectionId = models.CharField(max_length=300, null=True)

    class Meta:
        ordering = ("-sectionName",)

    def __str__(self):
        return self.sectionName, ':', self.stockName

class SectionInfo(models.Model):
    sectionId = models.CharField(max_length=300, null=True)
    sectionName = models.CharField(max_length=300)
    desc = models.TextField(null=True)

    class Meta:
        ordering = ("-sectionName",)

class StockSectionTemp(models.Model):
    sectionName = models.CharField(max_length=300)
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    stockId2 = models.CharField(max_length=300, null=True) #华尔街见闻用
    sectionId = models.CharField(max_length=300, null=True)

    class Meta:
        ordering = ("-sectionName",)

    def __str__(self):
        return self.sectionName, ':', self.stockName

class SectionInfoTemp(models.Model):
    sectionId = models.CharField(max_length=300, null=True)
    sectionName = models.CharField(max_length=300)
    desc = models.TextField(null=True)

    class Meta:
        ordering = ("-sectionName",)

class News(models.Model):
    datetime = models.CharField(max_length=32)
    title = models.CharField(max_length=512)
    isbull = models.CharField(max_length=32)
    content = models.TextField(null=True)
    stocks = models.CharField(max_length=512, null=True)
    sections = models.CharField(max_length=512, null=True)

    class Meta:
        ordering = ("-datetime",)

    def __str__(self):
        return self.datetime, ':', self.title

class StockComment(models.Model):
    stockId = models.CharField(max_length=32)
    comment = models.TextField()
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    created = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ("-like",)

    def __str__(self):
        return self.stockId, ':', self.comment

class StockWatchList(models.Model):
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300)
    priority = models.IntegerField(default=0)

    class Meta:
        ordering = ("priority",)

    def __str__(self):
        return self.stockId, ':', self.stockName

class ImportantStock(models.Model):
    stockId = models.CharField(max_length=300)
    stockName = models.CharField(max_length=300, blank=True)
    position = models.IntegerField(default=0)

    class Meta:
        ordering = ("position",)

    def __str__(self):
        return self.stockId, ':', self.position

class ImportantStockMarket(models.Model):
    stockId = models.CharField(max_length=30)
    stockName = models.CharField(max_length=100, blank=True)
    position = models.IntegerField(default=0)
    increaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    increaseRateStr = models.CharField(max_length=100, blank=True)
    limitUpTime = models.CharField(max_length=30)
    sections = models.CharField(max_length=300)
    klineType = models.CharField(max_length=300)

    class Meta:
        ordering = ("position",)

    def __str__(self):
        return self.stockId, ':', self.position

class StockMarketIndex(models.Model):
    date = models.CharField(max_length=10)
    #sh
    indexSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateSH = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrSH = models.CharField(max_length=100, blank=True)
    increaseStockSH = models.IntegerField(default=0)
    decreaseStockSH = models.IntegerField(default=0)
    flatStockSH = models.IntegerField(default=0)
    limitupStcokSH = models.IntegerField(default=0)
    limitdownStcokSH = models.IntegerField(default=0)
    longRedStcokSH = models.IntegerField(default=0)
    longGreenStcokSH = models.IntegerField(default=0)
    #sz
    indexSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateSZ = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrSZ = models.CharField(max_length=100, blank=True)
    increaseStockSZ = models.IntegerField(default=0)
    decreaseStockSZ = models.IntegerField(default=0)
    flatStockSZ = models.IntegerField(default=0)
    limitupStcokSZ = models.IntegerField(default=0)
    limitdownStcokSZ = models.IntegerField(default=0)
    longRedStcokSZ = models.IntegerField(default=0)
    longGreenStcokSZ = models.IntegerField(default=0)
    #zxb
    indexZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateZXB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrZXB = models.CharField(max_length=100, blank=True)
    increaseStockZXB = models.IntegerField(default=0)
    decreaseStockZXB = models.IntegerField(default=0)
    flatStockZXB = models.IntegerField(default=0)
    limitupStcokZXB = models.IntegerField(default=0)
    limitdownStcokZXB = models.IntegerField(default=0)
    longRedStcokZXB = models.IntegerField(default=0)
    longGreenStcokZXB = models.IntegerField(default=0)
    #cyb
    indexCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateCYB = models.DecimalField(max_digits=32, decimal_places=2)
    indexIncreaseRateStrCYB = models.CharField(max_length=100, blank=True)
    increaseStockCYB = models.IntegerField(default=0)
    decreaseStockCYB = models.IntegerField(default=0)
    flatStockCYB = models.IntegerField(default=0)
    limitupStcokCYB = models.IntegerField(default=0)
    limitdownStcokCYB = models.IntegerField(default=0)
    longRedStcokCYB = models.IntegerField(default=0)
    longGreenStcokCYB = models.IntegerField(default=0)
    #total
    limitupStcokTotal = models.IntegerField(default=0)
    limitupNormalStcokTotal = models.IntegerField(default=0)
    limitupOneTypeStcokTotal = models.IntegerField(default=0)
    limitupTTypeStcokTotal = models.IntegerField(default=0)
    limitupFirstStcokTotal = models.IntegerField(default=0)
    limitupSencondStcokTotal = models.IntegerField(default=0)
    limitupThirdStcokTotal = models.IntegerField(default=0)
    badLimitupStcokTotal = models.IntegerField(default=0)
    badLimitupFirstStcokTotal = models.IntegerField(default=0)
    badLimitupSencondStcokTotal = models.IntegerField(default=0)
    badLimitupThirdStcokTotal = models.IntegerField(default=0)
    limitdownStcokTotal = models.IntegerField(default=0)
    limitdownFirstStcokTotal = models.IntegerField(default=0)
    limitdownSencondStcokTotal = models.IntegerField(default=0)
    limitdownThirdStcokTotal = models.IntegerField(default=0)

    class Meta:
        ordering = ("-date",)

    def __str__(self):
        return self.date

class SectionIncreaseInfo(models.Model):
    date = models.CharField(max_length=10)
    sectionName = models.CharField(max_length=300)
    sectionIncreaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed2minRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed2minRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed5MinRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed5MinRateStr = models.CharField(max_length=300)
    sectionIncreaseSpeed30MinRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseSpeed30MinRateStr = models.CharField(max_length=300)

    class Meta:
        ordering = ("-date",)

    def __str__(self):
        return self.sectionName

class SectionMarketInfo(models.Model):
    date = models.CharField(max_length=10, blank=True)
    sectionName = models.CharField(max_length=300)
    sectionIncreaseRate = models.DecimalField(max_digits=32, decimal_places=10)
    sectionIncreaseRateStr = models.CharField(max_length=300)
    increaseCount = models.IntegerField(default=0)
    decreaseCount = models.IntegerField(default=0)
    totalCount = models.IntegerField(default=0)
    limitUpCount = models.IntegerField(default=0)
    limitUpStocksShow = models.CharField(max_length=300, blank=True)
    limitUpStocksHidden = models.CharField(max_length=300, blank=True)
    badLimitUpCount = models.IntegerField(default=0)
    badLimitUpStocksShow = models.CharField(max_length=300, blank=True)
    badLimitUpStocksHidden = models.CharField(max_length=300, blank=True)
    threeStraightLimitUp = models.IntegerField(default=0)
    specialStockShow = models.CharField(max_length=300, blank=True)
    specialStockHidden = models.CharField(max_length=300, blank=True)
    newsList = []

    class Meta:
        ordering = ("-sectionIncreaseRate",)

    def __str__(self):
        return self.sectionName, ':', self.sectionIncreaseRateStr

class StockLimitUp(models.Model):
    date = models.CharField(max_length=10)
    stockId = models.CharField(max_length=32)
    stockName = models.CharField(max_length=100)
    limitUpInfo = models.CharField(max_length=100)
    limitUpTime = models.CharField(max_length=32)
    rank = models.IntegerField(default=0)

    class Meta:
        ordering = ("rank",)

    def __str__(self):
        return self.stockId, ':', self.limitUpInfo

class StockIncreaseFastWithAmount(models.Model):
    date = models.CharField(max_length=10)
    stockId = models.CharField(max_length=32)
    stockName = models.CharField(max_length=100)
    time = models.CharField(max_length=30, blank=True)

    class Meta:

templates/article/column/article_column.html
{% extends "article/base.html"%}
{% load staticfiles %}
{% block title %}article column{% endblock%}
{% block content%}
<div>
    <p class="text-right"><button class="btn btn-primary" id="add_column" onclick="add_column()">add column</button></p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this,{{column.id}})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this,{{column.id}})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了</p>
        {% endfor%}
    </table>
</div>
<script type="text/javascript" src="{% static "js/jquery.js"%}"></script>
<script type="text/javascript" src="{% static "js/layer.js"%}"></script>
<script type="text/javascript">
    function add_column(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"add column",
            content:'<div class="text-center style="margin-top:20px><p>请输入栏目名称</p><p>{{column_form.column}}</p></div>',
            btn:['confirm','cancel'],
            yes:function(index,layero){
                column_name = $('#id_column').val();
                $.ajax({
                    url:'{% url "article:article_column"%}',
                    type:'POST',
                    data:{"column":column_name},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("error");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function edit_column(the,column_id){
        var name = $(the).parents("tr").children("td").eq(1).text()
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"edit column",
            content:'<div class="text-center style="margin-top:20px><p>请编辑栏目名称</p><p><input type="text" id="new_name" value="' + name +'"></p></div>',
            btn:['confirm','cancel'],
            yes:function(index,layero){
                new_name = $('#new_name').val();
                $.ajax({
                    url:'{% url "article:rename_article_column"%}',
                    type:'POST',
                    data:{"column_id":column_id,"column_name":new_name},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("error");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

    function del_column(the,column_id){
        var name = $(the).parents("tr").children("td").eq(1).text()
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:"delete column",
            content:'<div class="text-center style="margin-top:20px><p>是否确定删除{' + name +'}栏目</p></div>',
            btn:['confirm','cancel'],
            yes:function(index,layero){
                new_name = $('#new_name').val();
                $.ajax({
                    url:'{% url "article:del_article_column"%}',
                    type:'POST',
                    data:{"column_id":column_id},
                    success:function(e){
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("error");
                        }
                    },
                });
            },
            btn2:function(index,layero){
                layer.close(index)
            }
        });
    }

</script>
{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html"%}
{% load staticfiles %}

{% block title %}articles list{% endblock %}

{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/editormd.preview.css' %}" />
<div>
    <header>
        <h1>{{article.title}}</h1>
        <p>{{user.username}}</p>
    </header>

    <div id="editormd-view">
        <textarea id="append-test" style="display: none">
            {{article.body}}
        </textarea>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/marked.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/prettify.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/raphael.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/underscore.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/sequence-diagram.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/flowchart.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/lib/jquery.flowchart.min.js'%}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.js'%}"></script>

<script type="text/javascript">

$(function(){
    editormd.markdownToHTML("editormd-view",{
        htmlDecode:"style,script,iframe",
        emoji:true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram:true,
    });
});
</script>

{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html "%}

{% load staticfiles %}

{% block title %}articles list {% endblock%}

{% block content%}
<div>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
        <tr id="{{article.id}}">
            <td>{{ forloop.counter }}</td>
            <td><a href="{{article.get_absolute_url}}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>--</td>
        </tr>
        {% endfor%}
    </table>
    {% include "paginator.html "%}
</div>

{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html"%}
{% load staticfiles %}
{% block title %}article post{% endblock%}
{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/style.css '%}">
<link rel="stylesheet" type="text/css" href="{% static 'editor/css/editormd.css '%}">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-right"><span>标题</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-right"><span>栏目</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{column.id}}">{{column.column}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-right"><span>内容</span></div>
            <div class="col-md-10 text-left">
                <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display: none;" id="id_body"></textarea>
                </div>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发  布" onclick="publish_article()">
        </div>
    </form>
</div>
<script type="text/javascript" src="{% static "js/jquery.js"%}"></script>
<script type="text/javascript" src="{% static "js/layer.js"%}"></script>
<script type="text/javascript" src="{% static "editor/editormd.min.js"%}"></script>
<script type="text/javascript">
    function publish_article(){
        var title = $("#id_title").val();
        var column_id = $("#which_column").val();
        var body = $("#id_body").val();
        $.ajax({
            url:'{% url "article:article_post"%}',
            type:'POST',
            data:{"title":title,"body":body,"column_id":column_id},
            success:function(e){
                if(e=='1'){
                    layer.msg("good");
                    location.href = "{% url 'article:article_list' %}";
                }else if(e=='2'){
                    layer.msg("error1");
                }else{
                    layer.msg("error2");
                }
            },
        });
    }

    $(function(){
        var editor = editormd("editormd",{
            width:"100%",
            height:640,
            syncScrolling:"single",
            path:"{% static 'editor/lib/'%}"
        });
    });
</script>
{% endblock %}