account/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^login/$', views.user_login,name='user_login'),
    url(r'^login/$', auth_views.login,name='user_login'),
    url(r'^logout/$', auth_views.logout,{"template_name": "account/logout.html"},name='user_logout'),
    url(r'^new-login/$', auth_views.login,{"template_name": "account/login.html"}),
    url(r'^register/$', views.register,name="user_register"),
    url(r'^password-change/$', auth_views.password_change,{"post_change_redirect":"/account/password-change-done"},name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done,name="password_change_done"),
    url(r'^password-reset/$', auth_views.password_reset,
        {"template_name":"account/password_reset_form.html",
        "email_template_name":"account/password_reset_email.html",
        "subject_template_name":"account/password_reset_subject.txt",
        "post_reset_redirect":"/account/password-reset-done"},
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.password_reset_done,
        {"template_name":"account/password_reset_done.html"},
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)$', auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html",
        "post_reset_redirect":"/account/password-reset-conplete"},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name":"account/password_reset_complete.html"},
        name="password_reset_complete"),
    url(r'^my-information/$', views.myself,name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit,name="edit_my_information"),
    url(r'^my-image/$', views.my_image,name="my_image"),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    #url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^stock/', include('stock.urls', namespace='stock', app_name='stock')),
]

stock/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from .apps import StockConfig
#import xlrd, xlwt, sys, os, datetime
#sys.path.insert(0, StockConfig.TSL_PATH)
#import TSLPy3
#if TSLPy3.Logined():
#    pass
#else:
#    result = TSLPy3.DefaultConnectAndLogin(StockConfig.TSL_LOGIN_NAME)
#    print(result[0])

urlpatterns = [
    
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
   <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body style="background:transparent;">
   {% include "header.html"%}
	<div class="container">
		{% block content %}
		{% endblock%}
	</div>
	{% include "footer.html"%}
	
   {% block javascript%}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right @ 2018 jyu</p>
</div>

templates/header.html
{% load staticfiles %}

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://itdiffer.com">
                <img src="{% static 'images/logo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change'%}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information'%}">个人信息</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">LOGOUT</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                {% endif%}
            </ul>
        </div>
    </nav>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>

templates/paginator.html
<div class="pagination">
    <span class="step-link">
        <a href="?page=1">第一页</a>
        {% if page.has_previous %}
            <a href="?page={{page.prevoius_page_number}}">上一页</a>
        {% endif %}
        <span class="current">
        Page {{page.number}} of {{page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">下一页</a>
        {% endif %}
        <a href="?page={{page.paginator.num_pages}}">最后一页</a>
    </span>
</div>